#!/bin/bash

echo "Installing dotfiles..."

# Working directory
PWD=`pwd`

function remove_config {
  if [ -h "$1" ]
  then
    unlink "$1"
  elif [ -f "$1" ]
  then
    rm "$1"
  fi
}

function install_bash_config {
  echo "  installing Bash profile "
  local readonly path="$HOME/.bash_profile"
  remove_config "$path"
  ln -s "$PWD/.bash_profile" "$path"
}

function install_zsh_config {
  echo "  installing ZSH profile "
  local readonly path="$HOME/.zprofile"
  remove_config "$path"
  ln -s "$PWD/.zprofile" "$path"

  echo "  installing ZSH config "
  local readonly path="$HOME/.zshrc"
  remove_config "$path"
  ln -s "$PWD/.zshrc" "$path"
}

function install_git_config {
  echo "  installing Git configuration "
  local readonly path="$HOME/.gitignore"
  remove_config "$path"
  ln -s "$PWD/.gitignore" "$path"
  git config --global core.excludesfile "$path"
}

function install_compose_config {
  echo "  installing Composer descriptors "

  local readonly path="$HOME/.composer"
  local readonly lockpath="$path/composer.lock"
  local readonly jsonpath="$path/composer.json"

  mkdir -p "$path"

  remove_config "$lockpath"
  remove_config "$jsonpath"

  ln -s "$PWD/.composer/composer.json" "$jsonpath"
  ln -s "$PWD/.composer/composer.lock" "$lockpath"
}

install_bash_config
install_zsh_config
install_git_config
install_compose_config

echo "Installation finished!"
