#!/bin/bash

echo "Installing dotfiles..."

# Working directory
PWD=`pwd`

echo "  installing Bash profile "
unlink ~/.bash_profile
ln -s $PWD/.bash_profile ~/.bash_profile

echo "  installing global Git ignore configuration "
unlink ~/.gitignore
ln -s $PWD/.gitignore ~/.gitignore

echo "  populating generic Git configuration "
git config --global core.excludesfile ~/.gitignore

echo "  installing terminal-notifier "
gem install terminal-notifier

echo "  installing Composer descriptors "
mkdir -p ~/.composer
unlink ~/.composer/composer.json
unlink ~/.composer/composer.lock
ln -s $PWD/.composer/composer.json ~/.composer/composer.json
ln -s $PWD/.composer/composer.lock ~/.composer/composer.lock

echo "  installing keyboard bindings "
# TODO: check if Karabiner is installed.
# TODO: check against file/symlink.
unlink "$HOME/Library/Application Support/Karabiner/private.xml"
rm "$HOME/Library/Application Support/Karabiner/private.xml"
ln -s "$HOME/.dotfiles/karabiner/private.xml" "$HOME/Library/Application Support/Karabiner/private.xml"

echo "Installation finished!"
